### ISSUE TITLE
改造成 spmjs.org 官方程序

### ISSUE THREAD

**Issue by lepture** [spmjs/spm-yuan#2]
原 spmjs.org 网站是 python 的，不利于其他人参与。

打算在此基础上改造为通用的完整的程序。

需要的库：
1. https://github.com/andris9/Nodemailer

应用：
1. express
2. jade
3. 无数据库，使用文件存储

前端考虑用 angular.js

**Comment by edokeh** [comment]
1. 用 express 改造了一下，之前用 connect 是因为当时还不太了解 express
2. 不喜欢 jade，同不喜欢 slim, haml 等等，感觉效率上没有本质提高
3. 继续无数据库，但是用 Node.js 写业务逻辑真的好蛋疼
4. angular... 弱弱的说我喜欢 Backbone ...
