### ISSUE TITLE
移除内置的 cluster，改为依赖外部工具

### ISSUE THREAD

**Issue by edokeh** [spmjs/spm-yuan#4]
不再内置多线程的支持，而交给外部程序完成，比如 forever, pm2 等
短暂比较了一下，决定选择 https://github.com/Unitech/pm2

**Comment by lepture** [comment]
成熟的方案应该是 supervisor，虽然是 python 的

http://supervisord.org/

**Comment by edokeh** [comment]
。。。。好的，不过暂时先这么弄吧，我是 Ruby 党，你懂的
