### ISSUE TITLE
本地源服务器的搭建问题

### ISSUE THREAD

**Issue by sofond** [spmjs/spm-yuan#7]
搜索了挺久，就spm1.x的文档有详细的本地源的搭建方法，但是那些现在都不能用了，参照spm-yuan里面的说明文档，能启动一个本地源服务器，但是spm doc publish -s local 的时候，提示:exit: not found 。这个错误是源服务器的创建有问题吗？

本地源服务的搭建再找不到其它有用的资料了，请问我如果搭建一个本地源服务器？如何在一个文件里面部署为源存放的位置？

刚接触spm，还没完全搞明白，很想在公司推行推行起来，还望指教。

**Comment by edokeh** [comment]
`spm doc publish -s local` 这个命令是干嘛的？

**Comment by sofond** [comment]
@edokeh , local 是config定义的本地私有源，spm doc publish -s local 是想把文档发布到本地私有源中。

昨天再研究了一下，现在是不是可以理解为：spm-yuan 只是本地的临时源，spm publish 到本地源的都在.spm/cache 里面？？ spm-yuan 是无法支持文档发布服务的？就是本地spm-yuan是无法支持spm doc pubish 的？

Thanks

**Comment by sofond** [comment]
@edokeh , 如果本地要架设一个文档发布服务源，是不是得用https://github.com/lepture/yuan 这个？

现在有个需求场景：

前端人员写出一个模块/页面，本地可以用spm watch 来预览和修改。
前端人员spm publish 发布模块到本地源，spm doc publish 发布模块/页面 Demo到本地文档服务源。
后端程序、RA 、QA 通过文档服务源来Review/test 这个模块/页面 Demo。

**Comment by edokeh** [comment]
对的，spm-yuan 是以你的 cache 目录为目录的
 `spm doc publish` 这命令我没见过，是不是 spm1 的？
spm2 相对 spm1 基本是一个全新的东西，所以相应的源服务的接口也有很大不同，spm-yuan 是适配 spm2 的

**Comment by edokeh** [comment]
是这样的，目前的 http://spmjs.org 使用 https://github.com/lepture/yuan 这个项目的代码搭建的
而这个 spm-yuan 是为了方便搭建私服写的一个工具，与上面的 yuan 没有什么关系（yuan 使用 python 写的）
但是两者的对外 HTTP 接口基本一致，yuan 比 spm-yuan 接口更多一点

**Comment by lizzie** [comment]
spm doc xxx 主要是用于本地服务器的, 比如 spm doc watch, 就是起了个本地服务, 可以随时修改代码及 demo, 以便在本地调试, 而 spm doc publish 就是将 spm doc build 生成的 `_site` 站点(静态站点) 归档后传到 文档服务器上.

@sofond 你说的 

> 现在有个需求场景：

几点, 都是可以实现的. 没问题的. 我们公司内部也是这个流程, 你的理解是对的.

**Comment by edokeh** [comment]
@lizzie 
落伍了，spm doc 这命令是哪里的？文档上没见到啊，是另外一个插件？

**Comment by lizzie** [comment]
@edokeh spm doc 是 spm 的一个插件, 代码在 https://github.com/spmjs/spm-doc

**Comment by sofond** [comment]
Thanks @lizzie and @edokeh,

现在明白如果要实现本地文档服务器得用 https://github.com/lepture/yuan 这个项目的代码来搭建。
这个项目文档说明文档比较少，不是很明白如何去搭建一个内部文档服务器。

@lizzie 能否提点一下，非常感谢。

**Comment by afc163** [comment]
@sofond 

这个搭建很复杂，我们自己都搞不定。

**Comment by sofond** [comment]
非常感谢各位，我再研究研究，争取把我想要的场景都实现。

**Comment by lizzie** [comment]
https://github.com/lepture/yuan  按照上面搭建, 起个服务器, 再把服务地址添加到 `~/.spm/spmc` 中

例如: 

```
[source:local]
url = http://127.0.0.1:5000
auth = 
```

然后 `spm doc publish -s local` 这样就能上传到 本地起的服务器了.

PS: 文档和模块代码上传到的目录是 https://github.com/lepture/yuan/blob/master/conf/base_config.py#L45 中的 `WWW_ROOT` 字段, 文档其实都是静态的, 就是从 spm doc build 出来的  _site/  目录.

另外, yuan 中的 conf 是所有的配置文件. 我只看了 base_config.py 是 源服务站点的配置. 其他的配置就不清楚了. 你有问题可以直接问 @lepture

**Comment by edokeh** [comment]
我看看 doc 命令的接口吧，如果简单的话可以添加到 spm-yuan 里面

**Comment by lepture** [comment]
@edokeh 挺简单的，就是一个 post 上传文件的接口。
